// src/App.tsx
import { useState, useEffect, useMemo } from "react";
import { useTranslation } from "react-i18next";
import { Button, Menu, TextField, Slider, Switch } from "glassine-paper";
import PWABadge from "./PWABadge";
import SvgLightMode from "./icons/SvgLightMode";
import SvgDarkMode from "./icons/SvgDarkMode";
import SvgBrightnessAuto from "./icons/SvgBrightnessAuto";
import SvgMoreVert from "./icons/SvgMoreVert";
import SvgContentCopy from "./icons/SvgContentCopy";
import SvgRefresh from "./icons/SvgRefresh";
import SvgResetSettings from "./icons/SvgResetSettings";
import { version } from "../package.json";
import {
  charSetAll,
  charSetStd,
  charSetExt,
  defaultExcludedChars,
  generateChars,
  generatePassword,
} from "./honkipass.js";
import "./App.css";

const rowStyle: React.CSSProperties = {
  display: "flex",
  justifyContent: "center",
  alignItems: "center",
  padding: "0.5rem",
  gap: "0.5rem",
};

function App() {
  const { t, i18n } = useTranslation();

  const [menuOpen, setMenuOpen] = useState(false);
  const [lang, setLang] = useState("ja");
  const [brightness, setBrightness] = useState<"light" | "dark" | "light dark">(
    "light dark",
  );

  const [password, setPassword] = useState("abcdefghijklmnopqrstuvwxyz");
  const [message, setMessage] = useState("generated");
  const [error, setError] = useState(false);

  const lengthList = [6, 8, 10, 12, 16, 20, 24, 30, 36, 48, 64, 128];
  const [lengthIndex, setLengthIndex] = useState(1);
  const length = useMemo(
    () => lengthList[lengthIndex],
    [lengthIndex, lengthList],
  );
  const [preset, setPreset] = useState<"std" | "ext" | "manual">("std");
  const [lowerCase, setLowerCase] = useState(true);
  const [upperCase, setUpperCase] = useState(true);
  const [numerics, setNumerics] = useState(true);
  const [symbols, setSymbols] = useState(true);
  const [allTypes, setAllTypes] = useState(true);
  const [uniqueChars, setUniqueChars] = useState(true);
  const [applyExcluded, setApplyExcluded] = useState(true);
  const [excludedChars, setExcludedChars] = useState(defaultExcludedChars);

  const params = useMemo(
    () => ({
      length,
      preset,
      lowerCase,
      upperCase,
      numerics,
      symbols,
      allTypes,
      uniqueChars,
      applyExcluded,
      excludedChars,
    }),
    [
      length,
      preset,
      lowerCase,
      upperCase,
      numerics,
      symbols,
      allTypes,
      uniqueChars,
      applyExcluded,
      excludedChars,
    ],
  );

  const chars = useMemo(() => generateChars(params), [params]);
  const changed = useMemo(
    () =>
      params.length !== 8 ||
      params.preset !== "std" ||
      !params.lowerCase ||
      !params.upperCase ||
      !params.numerics ||
      !params.symbols ||
      !params.allTypes ||
      !params.uniqueChars ||
      !params.applyExcluded ||
      params.excludedChars !== defaultExcludedChars,
    [params],
  );

  const refresh = () => {
    setMessage("please wait");
    const generated = generatePassword(params, chars);
    if (generated) {
      setPassword(generated);
      setTimeout(() => {
        setMessage("generated");
        setError(false);
      }, 100);
    } else {
      setTimeout(() => {
        setMessage("try again");
        setError(true);
      }, 100);
    }
  };

  useEffect(() => {
    refresh();
  }, [params]);

  const copy = () => {
    navigator.clipboard.writeText(password);
    setMessage("please wait");
    setTimeout(() => {
      setMessage("copied");
    }, 100);
  };

  const reset = () => {
    setLengthIndex(1);
    setPreset("std");
    setLowerCase(true);
    setUpperCase(true);
    setNumerics(true);
    setSymbols(true);
    setAllTypes(true);
    setUniqueChars(true);
    setApplyExcluded(true);
    setExcludedChars(defaultExcludedChars);
  };

  useEffect(() => {
    document.documentElement.style.setProperty("color-scheme", brightness);
  }, [brightness]);

  return (
    <>
      <header>
        <img src="./favicon.svg" alt={t("app title")} />
        <h1>{t("app title")}</h1>
        <div className="hidden-xs">
          <Button
            name="language"
            type="select"
            size="xs"
            radius="square"
            icon={<span>En</span>}
            checked={lang === "en"}
            onClick={() => {
              setLang("en");
              i18n.changeLanguage("en");
            }}
          />
          <Button
            name="language"
            type="select"
            size="xs"
            radius="square"
            icon={<span>日</span>}
            checked={lang === "ja"}
            onClick={() => {
              setLang("ja");
              i18n.changeLanguage("ja");
            }}
          />
          <Button
            name="brightness-mode"
            type="select"
            size="xs"
            radius="square"
            icon={<SvgLightMode />}
            checked={brightness === "light"}
            onClick={() => setBrightness("light")}
          />
          <Button
            name="brightness-mode"
            type="select"
            size="xs"
            radius="square"
            icon={<SvgDarkMode />}
            checked={brightness === "dark"}
            onClick={() => setBrightness("dark")}
          />
          <Button
            name="brightness-mode"
            type="select"
            size="xs"
            radius="square"
            icon={<SvgBrightnessAuto />}
            checked={brightness === "light dark"}
            onClick={() => setBrightness("light dark")}
          />
        </div>
        <div className="hidden-sm">
          <Button
            size="xs"
            radius="square"
            variant="tonal"
            icon={<SvgMoreVert />}
            onClick={() => setMenuOpen(!menuOpen)}
          />
        </div>
      </header>
      {menuOpen && (
        <Menu
          id="main-menu"
          items={[
            {
              label: "English",
              active: lang === "en",
              onClick: () => {
                setLang("en");
                i18n.changeLanguage("en");
                setMenuOpen(false);
              },
            },
            {
              label: "日本語",
              active: lang === "ja",
              onClick: () => {
                setLang("ja");
                i18n.changeLanguage("ja");
                setMenuOpen(false);
              },
            },
            { divider: true },
            {
              leadingIcon: <SvgLightMode />,
              label: "Light Mode",
              active: brightness === "light",
              onClick: () => {
                setBrightness("light");
                setMenuOpen(false);
              },
            },
            {
              leadingIcon: <SvgDarkMode />,
              label: "Dark Mode",
              active: brightness === "dark",
              onClick: () => {
                setBrightness("dark");
                setMenuOpen(false);
              },
            },
            {
              leadingIcon: <SvgBrightnessAuto />,
              label: "Auto",
              active: brightness === "light dark",
              onClick: () => {
                setBrightness("light dark");
                setMenuOpen(false);
              },
            },
          ]}
        />
      )}
      <div id="result-area">
        <TextField
          id="result-field"
          value={password}
          leadingIcon={
            <button
              style={{ appearance: "none", border: "none", background: "none" }}
              onClick={() => refresh()}
            >
              <SvgRefresh />{" "}
            </button>
          }
          trailingIcon={
            <button
              style={{ appearance: "none", border: "none", background: "none" }}
              onClick={copy}
            >
              <SvgContentCopy />
            </button>
          }
          supportingText={t(message)}
          error={error}
          readonly
          innerStyle={{ fontFamily: "var(--monospace-font-family)" }}
        />
      </div>
      <main>
        <div>
          <div id="char-map">
            {charSetAll.split("").map((c) => (
              <span
                className={`${!chars.includes(c) ? "disabled" : ""} ${password.includes(c) ? "used" : ""}`}
              >
                {c}
              </span>
            ))}
          </div>
        </div>
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "start",
            padding: "0.5rem",
          }}
        >
          <Button
            variant="tonal"
            size="sm"
            icon={<SvgResetSettings />}
            onClick={() => reset()}
            disabled={!changed}
          />
          <Slider
            min={0}
            max={lengthList.length - 1}
            step={1}
            options={lengthList.map((_, index) => ({ value: index }))}
            value={lengthIndex}
            displayValue={`${length}`}
            showValueIndicator
            onChange={(value) => setLengthIndex(value)}
            style={{ width: "80%" }}
          />
        </div>
        <div style={rowStyle}>
          <Button
            type="select"
            name="preset"
            size="sm"
            label={t("std", { len: "" + charSetStd.length })}
            checked={preset === "std"}
            onClick={() => setPreset("std")}
          />
          <Button
            type="select"
            name="preset"
            size="sm"
            label={t("ext", { len: "" + charSetExt.length })}
            checked={preset === "ext"}
            onClick={() => setPreset("ext")}
          />
          <Button
            type="select"
            name="preset"
            size="sm"
            label={t("manual")}
            checked={preset === "manual"}
            onClick={() => setPreset("manual")}
          />
        </div>
        <div style={rowStyle}>
          <Button
            type="toggle"
            size="sm"
            label="abc"
            checked={lowerCase}
            onClick={() => setLowerCase(!lowerCase)}
            disabled={preset !== "manual"}
          />
          <Button
            type="toggle"
            size="sm"
            label="ABC"
            checked={upperCase}
            onClick={() => setUpperCase(!upperCase)}
            disabled={preset !== "manual"}
          />
          <Button
            type="toggle"
            size="sm"
            label="123"
            checked={numerics}
            onClick={() => setNumerics(!numerics)}
            disabled={preset !== "manual"}
          />
          <Button
            type="toggle"
            size="sm"
            label="@#$"
            checked={symbols}
            onClick={() => setSymbols(!symbols)}
            disabled={preset !== "manual"}
          />
        </div>
        <div style={{ ...rowStyle, justifyContent: "space-between" }}>
          <TextField
            label={t("excluded chars")}
            value={excludedChars}
            onChange={(e) => setExcludedChars(e.target.value)}
            disabled={preset !== "manual"}
            style={{ width: "75%" }}
            innerStyle={{ fontFamily: "var(--monospace-font-family)" }}
          />
          <Switch
            checked={applyExcluded}
            onClick={() => setApplyExcluded(!applyExcluded)}
            disabled={preset !== "manual"}
          />
        </div>
        <div style={{ ...rowStyle, justifyContent: "space-between" }}>
          {t("all types")}
          <Switch checked={allTypes} onClick={() => setAllTypes(!allTypes)} />
        </div>
        <div style={{ ...rowStyle, justifyContent: "space-between" }}>
          {t("unique chars")}
          <Switch
            checked={uniqueChars}
            onClick={() => setUniqueChars(!uniqueChars)}
          />
        </div>
      </main>
      <footer>
        <span>&copy; 2024, 2025 Michinobu Maeda</span>
        <a href="https://github.com/MichinobuMaeda/glassine-paper">GitHub</a>
        <span>v{version}</span>
      </footer>
      <PWABadge />
    </>
  );
}

export default App;

// src/App.svelte
<script>
  import PWABadge from "./lib/PWABadge.svelte";

  import IconButtonFilled from "./lib/components/IconButtonFilled.svelte";
  import GroupedButton from "./lib/components/GroupedButton.svelte";
  import IconButtonOutlined from "./lib/components/IconButtonOutlined.svelte";
  import IconButtonTonal from "./lib/components/IconButtonTonal.svelte";
  import ButtonTonal from "./lib/components/ButtonTonal.svelte";
  import Switch from "./lib/components/Switch.svelte";
  import Filter from "./lib/components/Filter.svelte";
  import TextFieldOutlined from "./lib/components/TextFieldOutlined.svelte";
  import { version } from "../package.json";
  import { langButtonName, m, toggleLang } from "./lib/i18n.svelte.js";

  import SvgResetSettings from "./lib/icons/SvgResetSettings.svelte";
  import SvgRemove from "./lib/icons/SvgRemove.svelte";
  import SvgAdd from "./lib/icons/SvgAdd.svelte";
  import SvgContentCopy from "./lib/icons/SvgContentCopy.svelte";
  import SvgRefresh from "./lib/icons/SvgRefresh.svelte";

  import {
    charSetAll,
    getDefaultValues,
    generateChars,
    generatePassword,
    charSetStd,
    charSetExt,
    minLength,
    isDefaultValues,
  } from "./lib/honkipass.js";

  let param = $state(getDefaultValues());
  let chars = $derived(generateChars(param));
  let password = $derived(generatePassword(param));
  let passwordMessage = $state("");
  let message = $derived(
    passwordMessage === "copied"
      ? m().copied()
      : passwordMessage === "generated"
        ? m().generated()
        : passwordMessage === "wait"
          ? "..."
          : "",
  );
  let error = $derived(passwordMessage === "try_again" ? m().try_again() : "");

  $effect(() => {
    if (password) {
      passwordMessage = "wait";
      setTimeout(() => {
        passwordMessage = "generated";
      }, 100);
    } else {
      passwordMessage = "try_again";
    }
  });

  const copy = () => {
    navigator.clipboard.writeText(password);
    passwordMessage = "wait";
    setTimeout(() => {
      passwordMessage = "copied";
    }, 100);
  };
</script>

<svelte:head>
  <title>{m().appTitle()} v5</title>
</svelte:head>

<div
  class="flex flex-row justify-center
    bg-lightSurfaceVariant dark:bg-darkSurfaceVariant"
>
  <div
    class="flex w-full max-w-screen-sm flex-col
      bg-lightBackground dark:bg-darkBackground
      text-lightOnBackground dark:text-darkOnBackground"
  >
    <div class="flex min-h-screen flex-col justify-between">
      <header
        class="flex
          bg-lightPrimaryContainer dark:bg-darkPrimaryContainer
          text-lightOnPrimaryContainer dark:text-darkOnPrimaryContainer"
      >
        <h1 class="flex flex-row mr-auto p-1 text-xl">
          <img
            src="/favicon.svg"
            alt="Honkipass v5 Logo"
            class="mr-2 h-8 w-8"
          />
          {m().appTitle()} v5
        </h1>
        <div class="flex flex-row px-2">
          <button
            class="text-lightPrimary dark:text-darkPrimary"
            onclick={toggleLang}>&raquo; {langButtonName()}</button
          >
        </div>
      </header>

      <PWABadge />

      <main class="mb-auto flex justify-center">
        <div class="flex flex-col gap-4 px-1 pb-6 pt-4 sm:gap-8 sm:pt-8">
          <div class="flex justify-center">
            <div class="font-mono">
              {#each charSetAll.split("") as char, index}
                {#if index > 0 && index % 32 === 0}
                  <br />
                {/if}{#if password.indexOf(char) >= 0}
                  <span
                    class="bg-lightPrimaryContainer
                    text-lightOnPrimaryContainer sm:px-0.5
                    dark:bg-darkPrimaryContainer dark:text-darkOnPrimaryContainer"
                    >{char}</span
                  >
                {:else if chars.indexOf(char) >= 0}
                  <span class="sm:px-0.5">{char}</span>
                {:else}
                  <span class="opacity-30 sm:px-0.5">{char}</span>
                {/if}
              {/each}
            </div>
          </div>
          <div class="flex flex-row gap-2 sm:gap-8">
            <div class="grow">
              <TextFieldOutlined
                id="password"
                value={password}
                label={m().password()}
                readonly
                monospace
                {message}
                {error}
              />
            </div>
            <span class="flex gap-4 pt-2 sm:gap-8">
              <IconButtonTonal
                id="refresh"
                icon={SvgRefresh}
                onClick={() => {
                  param = { ...param };
                }}
              />
              <IconButtonFilled
                id="copy"
                icon={SvgContentCopy}
                onClick={copy}
                disabled={!!error}
              />
            </span>
          </div>

          <div class="flex flex-row gap-4 sm:gap-8">
            <IconButtonOutlined
              id="reset"
              icon={SvgResetSettings}
              onClick={() => {
                param = getDefaultValues();
              }}
              disabled={isDefaultValues(param)}
            />
            <div
              class="mt-2 w-20 text-right
              text-lightOnBackground dark:text-darkOnBackground"
            >
              {m().length({ len: param.length })}
            </div>
            <IconButtonTonal
              id="lengthDn"
              icon={SvgRemove}
              onClick={() => {
                if (param.length > minLength) {
                  param.length--;
                }
              }}
            />
            <IconButtonTonal
              id="lengthUp"
              icon={SvgAdd}
              onClick={() => {
                param.length++;
              }}
            />
            <ButtonTonal
              id="lengthUp4"
              label="+4"
              onClick={() => {
                param.length += 4;
              }}
            />
          </div>
          <div class="flex flex-row justify-center gap-2 sm:gap-8">
            <GroupedButton
              id="charSets"
              items={[
                {
                  label: m().std({ len: charSetStd.length }),
                  value: "s",
                },
                {
                  label: m().ext({ len: charSetExt.length }),
                  value: "e",
                },
                {
                  label: m().manual(),
                  value: "m",
                },
              ]}
              bind:value={param.charSet}
            />
          </div>
          <div class="flex flex-row gap-2 sm:gap-4">
            <Switch id="useAllType" bind:checked={param.useAllTypes} />
            <span class="mt-1">{m().all_types()}</span>
          </div>
          <div class="flex flex-row gap-2 sm:gap-4">
            <Switch id="disallowRepeatUse" bind:checked={param.uniqueChars} />
            <span class="mt-1">{m().unique_chars()}</span>
          </div>
          <div class="flex flex-row justify-between gap-2 sm:gap-4">
            <Filter
              id="useUpperCase"
              bind:checked={param.useUpperCase}
              label="ABC"
              disabled={param.charSet !== "m"}
            />
            <Filter
              id="useLowerCase"
              bind:checked={param.useLowerCase}
              label="abc"
              disabled={param.charSet !== "m"}
            />
            <Filter
              id="useNumerics"
              bind:checked={param.useNumerics}
              label="123"
              disabled={param.charSet !== "m"}
            />
            <Filter
              id="useSymbol"
              bind:checked={param.useSymbols}
              label="@#$"
              disabled={param.charSet !== "m"}
            />
          </div>
          <div class="flex flex-row gap-2 sm:gap-4">
            <span class="pt-3">
              <Filter
                id="disallowExclusives"
                bind:checked={param.disallowExcluded}
                label={m().excl()}
                disabled={param.charSet !== "m"}
              />
            </span>
            <span class="grow">
              <TextFieldOutlined
                id="TextFieldOutlined1"
                label={m().excluded_chars()}
                bind:value={param.excluded}
                message=""
                disabled={param.charSet !== "m" || !param.disallowExcluded}
                monospace
              />
            </span>
          </div>
        </div>
      </main>
      <footer
        class="flex flex-row gap-1 text-base px-4 py-1
          bg-lightSecondary dark:bg-darkSecondary
          text-lightOnSecondary dark:text-darkOnSecondary"
      >
        © 2024 Michinobu Maeda
        <a
          class="mx-2 underline underline-offset-2
            text-lightInversePrimary dark:text-darkInversePrimary"
          href="https://github.com/MichinobuMaeda/honkipass5"
        >
          GitHub
        </a>
        v{version}
      </footer>
    </div>
  </div>
</div>
