// src/App.svelte
<script>
  import PWABadge from "./lib/PWABadge.svelte";

  import IconButtonFilled from "./lib/components/IconButtonFilled.svelte";
  import GroupedButton from "./lib/components/GroupedButton.svelte";
  import IconButtonOutlined from "./lib/components/IconButtonOutlined.svelte";
  import IconButtonTonal from "./lib/components/IconButtonTonal.svelte";
  import ButtonTonal from "./lib/components/ButtonTonal.svelte";
  import Switch from "./lib/components/Switch.svelte";
  import Filter from "./lib/components/Filter.svelte";
  import TextFieldOutlined from "./lib/components/TextFieldOutlined.svelte";
  import { version } from "../package.json";
  import { langButtonName, m, toggleLang } from "./lib/i18n.svelte.js";

  import SvgResetSettings from "./lib/icons/SvgResetSettings.svelte";
  import SvgRemove from "./lib/icons/SvgRemove.svelte";
  import SvgAdd from "./lib/icons/SvgAdd.svelte";
  import SvgContentCopy from "./lib/icons/SvgContentCopy.svelte";
  import SvgRefresh from "./lib/icons/SvgRefresh.svelte";

  import {
    charSetAll,
    getDefaultValues,
    generateChars,
    generatePassword,
    charSetStd,
    charSetExt,
    minLength,
    isDefaultValues,
  } from "./lib/honkipass.js";

  let param = $state(getDefaultValues());
  let chars = $derived(generateChars(param));
  let password = $derived(generatePassword(param));
  let passwordMessage = $state("");
  let message = $derived(
    passwordMessage === "copied"
      ? m().copied()
      : passwordMessage === "generated"
        ? m().generated()
        : passwordMessage === "wait"
          ? "..."
          : "",
  );
  let error = $derived(passwordMessage === "try_again" ? m().try_again() : "");

  $effect(() => {
    if (password) {
      passwordMessage = "wait";
      setTimeout(() => {
        passwordMessage = "generated";
      }, 100);
    } else {
      passwordMessage = "try_again";
    }
  });

  const copy = () => {
    navigator.clipboard.writeText(password);
    passwordMessage = "wait";
    setTimeout(() => {
      passwordMessage = "copied";
    }, 100);
  };
</script>

<svelte:head>
  <title>{m().appTitle()} v5</title>
</svelte:head>

<div
  class="flex flex-row justify-center
    bg-lightSurfaceVariant dark:bg-darkSurfaceVariant"
>
  <div
    class="flex w-full max-w-screen-sm flex-col
      bg-lightBackground dark:bg-darkBackground
      text-lightOnBackground dark:text-darkOnBackground"
  >
    <div class="flex min-h-screen flex-col justify-between">
      <header
        class="flex
          bg-lightPrimaryContainer dark:bg-darkPrimaryContainer
          text-lightOnPrimaryContainer dark:text-darkOnPrimaryContainer"
      >
        <h1 class="flex flex-row mr-auto p-1 text-xl">
          <img
            src="/favicon.svg"
            alt="Honkipass v5 Logo"
            class="mr-2 h-8 w-8"
          />
          {m().appTitle()} v5
        </h1>
        <div class="flex flex-row px-2">
          <button
            class="text-lightPrimary dark:text-darkPrimary"
            onclick={toggleLang}>&raquo; {langButtonName()}</button
          >
        </div>
      </header>

      <PWABadge />

      <main class="mb-auto flex justify-center">
        <div class="flex flex-col gap-4 px-1 pb-6 pt-4 sm:gap-8 sm:pt-8">
          <div class="flex justify-center">
            <div class="font-mono">
              {#each charSetAll.split("") as char, index}
                {#if index > 0 && index % 32 === 0}
                  <br />
                {/if}{#if password.indexOf(char) >= 0}
                  <span
                    class="bg-lightPrimaryContainer
                    text-lightOnPrimaryContainer sm:px-0.5
                    dark:bg-darkPrimaryContainer dark:text-darkOnPrimaryContainer"
                    >{char}</span
                  >
                {:else if chars.indexOf(char) >= 0}
                  <span class="sm:px-0.5">{char}</span>
                {:else}
                  <span class="opacity-30 sm:px-0.5">{char}</span>
                {/if}
              {/each}
            </div>
          </div>
          <div class="flex flex-row gap-2 sm:gap-8">
            <div class="grow">
              <TextFieldOutlined
                id="password"
                value={password}
                label={m().password()}
                readonly
                monospace
                {message}
                {error}
              />
            </div>
            <span class="flex gap-4 pt-2 sm:gap-8">
              <IconButtonTonal
                id="refresh"
                icon={SvgRefresh}
                onClick={() => {
                  param = { ...param };
                }}
              />
              <IconButtonFilled
                id="copy"
                icon={SvgContentCopy}
                onClick={copy}
                disabled={!!error}
              />
            </span>
          </div>

          <div class="flex flex-row gap-4 sm:gap-8">
            <IconButtonOutlined
              id="reset"
              icon={SvgResetSettings}
              onClick={() => {
                param = getDefaultValues();
              }}
              disabled={isDefaultValues(param)}
            />
            <div
              class="mt-2 w-20 text-right
              text-lightOnBackground dark:text-darkOnBackground"
            >
              {m().length({ len: param.length })}
            </div>
            <IconButtonTonal
              id="lengthDn"
              icon={SvgRemove}
              onClick={() => {
                if (param.length > minLength) {
                  param.length--;
                }
              }}
            />
            <IconButtonTonal
              id="lengthUp"
              icon={SvgAdd}
              onClick={() => {
                param.length++;
              }}
            />
            <ButtonTonal
              id="lengthUp4"
              label="+4"
              onClick={() => {
                param.length += 4;
              }}
            />
          </div>
          <div class="flex flex-row justify-center gap-2 sm:gap-8">
            <GroupedButton
              id="charSets"
              items={[
                {
                  label: m().std({ len: charSetStd.length }),
                  value: "s",
                },
                {
                  label: m().ext({ len: charSetExt.length }),
                  value: "e",
                },
                {
                  label: m().manual(),
                  value: "m",
                },
              ]}
              bind:value={param.charSet}
            />
          </div>
          <div class="flex flex-row gap-2 sm:gap-4">
            <Switch id="useAllType" bind:checked={param.useAllTypes} />
            <span class="mt-1">{m().all_types()}</span>
          </div>
          <div class="flex flex-row gap-2 sm:gap-4">
            <Switch id="disallowRepeatUse" bind:checked={param.uniqueChars} />
            <span class="mt-1">{m().unique_chars()}</span>
          </div>
          <div class="flex flex-row justify-between gap-2 sm:gap-4">
            <Filter
              id="useUpperCase"
              bind:checked={param.useUpperCase}
              label="ABC"
              disabled={param.charSet !== "m"}
            />
            <Filter
              id="useLowerCase"
              bind:checked={param.useLowerCase}
              label="abc"
              disabled={param.charSet !== "m"}
            />
            <Filter
              id="useNumerics"
              bind:checked={param.useNumerics}
              label="123"
              disabled={param.charSet !== "m"}
            />
            <Filter
              id="useSymbol"
              bind:checked={param.useSymbols}
              label="@#$"
              disabled={param.charSet !== "m"}
            />
          </div>
          <div class="flex flex-row gap-2 sm:gap-4">
            <span class="pt-3">
              <Filter
                id="disallowExclusives"
                bind:checked={param.disallowExcluded}
                label={m().excl()}
                disabled={param.charSet !== "m"}
              />
            </span>
            <span class="grow">
              <TextFieldOutlined
                id="TextFieldOutlined1"
                label={m().excluded_chars()}
                bind:value={param.excluded}
                message=""
                disabled={param.charSet !== "m" || !param.disallowExcluded}
                monospace
              />
            </span>
          </div>
        </div>
      </main>
      <footer
        class="flex flex-row gap-1 text-base px-4 py-1
          bg-lightSecondary dark:bg-darkSecondary
          text-lightOnSecondary dark:text-darkOnSecondary"
      >
        © 2024 Michinobu Maeda
        <a
          class="mx-2 underline underline-offset-2
            text-lightInversePrimary dark:text-darkInversePrimary"
          href="https://github.com/MichinobuMaeda/honkipass5"
        >
          GitHub
        </a>
        v{version}
      </footer>
    </div>
  </div>
</div>

// src/App.jsx
import PropTypes from "prop-types";
import { useState, useMemo, useEffect } from "react";
import { useTranslation } from "react-i18next";
import AppBar from "./xuan-paper/AppBar.jsx";
import PWABadge from "./xuan-paper/PWABadge.jsx";
import Button from "./xuan-paper/Button.jsx";
import ButtonGroup from "./xuan-paper/ButtonGroup.jsx";
import TextField from "./xuan-paper/TextField.jsx";
import Slider from "./xuan-paper/Slider.jsx";
import Switch from "./xuan-paper/Switch.jsx";
import ToggleLanguageButton from "./xuan-paper/ToggleLanguageButton.jsx";
import ToggleDarkModeButton from "./xuan-paper/ToggleDarkModeButton.jsx";

import SvgContentCopy from "./icons/SvgContentCopy.jsx";
import SvgRefresh from "./icons/SvgRefresh.jsx";
import SvgResetSettings from "./icons/SvgResetSettings.jsx";

import "./App.css";
import appLogo from "./assets/images/favicon.svg";
import version from "./version.js";
import {
  charSetAll,
  charSetStd,
  charSetExt,
  defaultExcludedChars,
  generateChars,
  generatePassword,
} from "./honkipass.js";

const bgColor = "bg-light-surface-variant dark:bg-dark-surface-variant";

const Row = ({ children }) => {
  return (
    <div
      className={`flex flex-wrap px-4 sm:px-8 gap-4 sm:gap-8
        justify-start items-center`}
    >
      {children}
    </div>
  );
};

Row.propTypes = {
  children: PropTypes.node,
};

const Char = ({ chr, disabled, used }) => (
  <span
    className={`px-0.5 ${
      disabled
        ? `bg-light-surface-container-high/50 dark:bg-dark-surface-container-high/50
              text-light-on-surface/30 dark:text-dark-on-surface/30`
        : used
          ? `bg-light-tertiary-container dark:bg-dark-tertiary-container
                text-light-tertiary dark:text-dark-tertiary`
          : "text-light-on-form dark:text-dark-on-form"
    }`}
  >
    {chr}
  </span>
);

Char.propTypes = {
  chr: PropTypes.string.isRequired,
  disabled: PropTypes.bool.isRequired,
  used: PropTypes.bool.isRequired,
};

/**
 * Main application component for Honkipass password generator.
 * @returns {JSX.Element} The application component.
 */
function App() {
  const { t } = useTranslation();

  const [password, setPassword] = useState("");
  const [message, setMessage] = useState("generated");

  const lengthList = [6, 8, 10, 12, 16, 20, 24, 30, 36, 48, 64, 128];
  const [lengthIndex, setLengthIndex] = useState(1);
  const length = useMemo(() => lengthList[lengthIndex]);

  const presetList = [
    { label: t("std", { len: charSetStd.length }), value: "s" },
    { label: t("ext", { len: charSetExt.length }), value: "e" },
    { label: t("manual"), value: "m" },
  ];
  const [preset, setPreset] = useState("s");

  const charTypeList = [
    { label: "abc", value: "l" },
    { label: "ABC", value: "u" },
    { label: "123", value: "n" },
    { label: "@#$", value: "s" },
  ];
  const charTypeValues = charTypeList.map((item) => item.value);
  const [charTypes, setCharTypes] = useState(charTypeValues);

  const [allTypes, setAllTypes] = useState(true);
  const [uniqueChars, setUniqueChars] = useState(true);
  const [applyExcluded, setApplyExcluded] = useState(true);
  const [excludedChars, setExcludedChars] = useState(defaultExcludedChars);

  const reset = () => {
    setLengthIndex(1);
    setPreset("s");
    setCharTypes(charTypeValues);
    setAllTypes(true);
    setUniqueChars(true);
    setApplyExcluded(true);
    setExcludedChars(defaultExcludedChars);
  };

  const params = useMemo(
    () => ({
      length,
      preset,
      lowerCase: charTypes.includes("l"),
      upperCase: charTypes.includes("u"),
      numerics: charTypes.includes("n"),
      symbols: charTypes.includes("s"),
      allTypes,
      uniqueChars,
      applyExcluded,
      excludedChars,
    }),
    [
      length,
      preset,
      charTypes,
      allTypes,
      uniqueChars,
      applyExcluded,
      excludedChars,
    ],
  );

  const chars = useMemo(() => generateChars(params), [params]);

  const changed = useMemo(
    () =>
      lengthIndex !== 1 ||
      preset !== "s" ||
      charTypeValues.length != charTypes.length ||
      charTypeValues.some((v) => !charTypes.includes(v)) ||
      !allTypes ||
      !uniqueChars ||
      !applyExcluded ||
      excludedChars !== defaultExcludedChars,
    [
      lengthIndex,
      preset,
      charTypes,
      allTypes,
      uniqueChars,
      applyExcluded,
      excludedChars,
    ],
  );

  const refresh = () => {
    setMessage("please wait");
    const generated = generatePassword(params, chars);
    if (generated) {
      setPassword(generated);
      setTimeout(() => {
        setMessage("generated");
      }, 100);
    } else {
      setTimeout(() => {
        setMessage("try again");
      }, 100);
    }
  };

  useEffect(() => {
    refresh();
  }, [params]);

  const copy = () => {
    navigator.clipboard.writeText(password);
    setMessage("please wait");
    setTimeout(() => {
      setMessage("copied");
    }, 100);
  };

  return (
    <div className="flex flex-col items-center">
      <AppBar
        appLogo={<img src={appLogo} alt={`${t("app title")} logo`} />}
        appName={t("app title")}
        suffix={[
          <ToggleLanguageButton key="language-toggle" />,
          <ToggleDarkModeButton key="dark-mode-toggle" />,
        ]}
      />
      <main
        className={`flex flex-col w-full sm:max-w-[640px] px-2 pb-14 pt-12`}
      >
        <PWABadge />
        <div
          className={`flex flex-row
           bg-light-form dark:bg-dark-form`}
        >
          <div
            className={`flex flex-row pl-2 pr-4 sm:pr-6 py-1 grow
              rounded-br-4xl ${bgColor}`}
          >
            <TextField
              value={password}
              message={t(message)}
              fontFamily="font-mono"
              prefix={
                <Button
                  icon={<SvgContentCopy />}
                  style="embedded"
                  onClick={copy}
                />
              }
              suffix={
                <Button
                  icon={<SvgRefresh />}
                  style="embedded"
                  onClick={refresh}
                />
              }
              width="w-full"
              readonly
            />
          </div>
          <div className={`flex flex-row pt-3 ${bgColor}`}>
            <div
              className={`flex flex-row px-4 sm:px-6 items-center rounded-t-4xl
                bg-light-form dark:bg-dark-form`}
            >
              <Button
                icon={<SvgResetSettings />}
                onClick={reset}
                disabled={!changed}
                style="outlined"
              />
            </div>
          </div>
        </div>
        <div
          className={`flex flex-col sm:px-2 pt-4 pb-8 gap-4
            rounded-tl-4xl rounded-b-4xl
            bg-light-form dark:bg-dark-form
            text-light-on-form dark:text-dark-on-form`}
        >
          <Row>
            <div className="flex flex-wrap font-mono">
              {charSetAll.split("").map((c) => (
                <Char
                  key={c}
                  chr={c}
                  disabled={!chars.includes(c)}
                  used={password.includes(c)}
                />
              ))}
            </div>
          </Row>
          <Row>
            <Slider
              count={lengthList.length - 1}
              value={lengthIndex}
              onChange={(v) => setLengthIndex(v)}
              width="w-3/5 sm:w-108"
            />
            <div className="flex grow justify-end">
              {t("length", { len: length })}
            </div>
          </Row>
          <Row>
            <ButtonGroup
              items={presetList}
              value={preset}
              onChange={(v) => setPreset(v)}
            />
          </Row>
          <Row>
            <ButtonGroup
              items={charTypeList}
              value={charTypes}
              onChange={(v) => {
                const prev = [...charTypes];
                if (v.length === 0) {
                  setCharTypes(prev);
                } else {
                  setCharTypes(v);
                }
              }}
              multiSelect
              disabled={preset !== "m"}
            />
          </Row>
          <Row>
            <TextField
              value={excludedChars}
              label={t("excluded chars")}
              onChange={(v) => setExcludedChars(v)}
              fontFamily="font-mono"
              width="grow"
              disabled={preset !== "m" || !applyExcluded}
            />
            <Switch
              value={applyExcluded}
              onChange={(v) => setApplyExcluded(v)}
              disabled={preset !== "m"}
            />
          </Row>
          <Row>
            <span className="flex grow">{t("all types")}</span>
            <Switch value={allTypes} onChange={(v) => setAllTypes(v)} />
          </Row>
          <Row>
            <span className="flex grow">{t("unique chars")}</span>
            <Switch value={uniqueChars} onChange={(v) => setUniqueChars(v)} />
          </Row>
        </div>
      </main>
      <footer>
        © 2024, 2025 Michinobu Maeda
        <a href="https://github.com/MichinobuMaeda/honkipass5">GitHub</a>
        {version}
      </footer>
    </div>
  );
}

export default App;
